import type { Metadata } from "next";

import "./globals.css";

import Navbar from "./layouts/navbar/Navbar";
import Footer from "./layouts/footer/page";
import Head from "next/head";
import { Nova_Round } from "next/font/google";

const nova_round = Nova_Round({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>

      <body>
      <Navbar/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
