import type { Metadata } from "next";

import "./globals.css";

import Navbar from "./layouts/navbar/page";
import Footer from "./layouts/footer/page";
import Head from "next/head";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header>
        <Navbar />
      </header>

      <body>{children}</body>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
